#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeCCMIO
#
# Description
#     Build the libccmio library
#
# ----------------------------------------------
# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
#------------------------------------------------------------------------------
# Run from third-party directory only
cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error (${0##*/}) : \$FOAM_EXT_LIBBIN not set"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------
# libccmio version from OpenFOAM etc/config.sh file
. $WM_PROJECT_DIR/etc/config.sh/functions
_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/ccmio)

ccmioPACKAGE=${ccmio_version:-libccmio-2.6.1}
targetType=lib
#------------------------------------------------------------------------------
usage()
{
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    /bin/cat<<USAGE

Usage: ${0##*/} [OPTION] [lib|libso] [libccmio-VERSION]
options:
  -help

* Compile the proprietary libccmio library
      $ccmioPACKAGE

  Users wishing to obtain the library should contact Siemens PLM (cd-adapco)
  for terms of use.

  After obtaining the $ccmioPACKAGE library, place in folder

      $WM_THIRD_PARTY_DIR/$ccmioPACKAGE/

  prior to running this script.

USAGE
    exit 1
}
#------------------------------------------------------------------------------

# Parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    lib|libso)
        targetType="$1"
        ;;
    libccmio-[1-9]*)
        ccmioPACKAGE="${1%%/}"
        ;;
    *)
        die "unknown option/argument: '$1'"
        ;;
    esac
    shift
done

# assert: directory must be available
[ -d "$ccmioPACKAGE" ] || die "missing source directory '$ccmioPACKAGE'"

#------------------------------------------------------------------------------
CCMIO_SOURCE_DIR=$sourceBASE/$ccmioPACKAGE
CCMIO_ARCH_PATH=$installBASE/$ccmioPACKAGE

#
# Build LIBCCMIO
#
echo "---------------"
(
    cd $CCMIO_SOURCE_DIR || exit 1
    incDIR=$CCMIO_ARCH_PATH/include/libccmio
    libDIR=$CCMIO_ARCH_PATH/lib

    mkdir -p $incDIR 2>/dev/null
    mkdir -p $libDIR 2>/dev/null

    cpMakeFiles libccmio 2>/dev/null
    if wmake $targetType
    then
        # make headers available:
        /bin/cp -pv libccmio/ccmio*.h $incDIR

        # relocate static libraries to sub-directory:
        if [ "$targetType" = lib ]
        then
            /bin/mv -v $FOAM_EXT_LIBBIN/libccmio.a $libDIR
        fi
    fi
)

#------------------------------------------------------------------------------
