#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeCmake
#
# Description
#     Build script for cmake
#
#------------------------------------------------------------------------------
# Special purpose script, no default cmake version.
unset cmakePACKAGE

#------------------------------------------------------------------------------
# Run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------
usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [OPTION] [cmake-VERSION]
options:
  -gcc              Force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
  -help

* build cmake
      ${cmakePACKAGE:-'unspecified version'}

USAGE
    exit 1
}
#------------------------------------------------------------------------------
# Ensure CMake gets the correct C/CC++ compiler
[ -n "$WM_CC" ]  && export CC="$WM_CC"
[ -n "$WM_CXX" ] && export CXX="$WM_CXX"

# Parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    -gcc)
        export CC=gcc   # use gcc/g++
        export CXX=g++
        ;;
    cmake-[1-9]*)
        cmakePACKAGE="${1%%/}"
        ;;
    *)
        die "unknown option/argument: '$1'"
        ;;
    esac
    shift
done

[ -n "$cmakePACKAGE" ] || die "The cmake-VERSION was not specified"

#------------------------------------------------------------------------------
#
# Build CMAKE
#   CMAKE_ARCH_PATH  : installation directory
#   CMAKE_SOURCE_DIR : location of the original sources

CMAKE_ARCH_PATH=$installBASE/$cmakePACKAGE
CMAKE_SOURCE_DIR=$WM_THIRD_PARTY_DIR/$cmakePACKAGE

if [ -d "$CMAKE_ARCH_PATH" -a -r "$CMAKE_ARCH_PATH/bin/cmake" ]
then
    echo "Already built: $cmakePACKAGE"
else
    echo "Starting build: $cmakePACKAGE"
    (
        buildDIR=$buildBASE/$cmakePACKAGE

        cd $CMAKE_SOURCE_DIR || exit 1
        make distclean 2>/dev/null

        rm -rf $buildDIR
        mkdir -p $buildDIR
        cd $buildDIR

        $CMAKE_SOURCE_DIR/bootstrap \
            --prefix=$CMAKE_ARCH_PATH \
        && time make -j $WM_NCOMPPROCS \
        && make install \
        && echo "Built: $cmakePACKAGE"
    ) || {
        echo "Error building: $cmakePACKAGE"
        exit 1
    }
fi

#------------------------------------------------------------------------------
